apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
type: Opaque
data:
    admin_user: YWRtaW4= # this is taken by running echo -n "admin" | base64
    admin_password: Z3JhZmFuYQ== # this is taken by running echo -n "grafana" | base64