apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: prom-data
  name: prom-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
